/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import view.form.karta.KupovinaForm;
import view.form.predstava.PredstaveForm;
import view.form.predstava.RepertoarForm;
import view.form.gledalac.LoyaltyClubForm;
import view.form.gledalac.PretragaClanovaKlubaForm;
import view.form.nalog.PretragaNalogaForm;
import domain.Gledalac;
import domain.Nalog;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.form.rezervacija.RezervacijeForm;

/**
 *
 * @author marij
 */
public class MainFormClient extends javax.swing.JFrame {

    Nalog n;
    /**
     * Creates new form MainFormClient
     */
    public MainFormClient(Nalog n) {
        initComponents();
        setLocationRelativeTo(null);
        this.n = n;
       
        
      
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblPozoriste = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miPrikazPodataka = new javax.swing.JMenuItem();
        miLoyaytyKlub = new javax.swing.JMenuItem();
        miPretragaNaloga = new javax.swing.JMenuItem();
        miPretragaClanova = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miPredstave = new javax.swing.JMenuItem();
        miPretrazi = new javax.swing.JMenuItem();
        miRezervacija = new javax.swing.JMenuItem();
        miKupovina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pozorište \"Gardoš\" - Početna strana");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/logo_pozoriste.png"))); // NOI18N

        lblPozoriste.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblPozoriste.setText("POZORIŠTE \"GARDOŠ\"");

        jLabel6.setText("Sibinjanin Janka bb");

        jLabel7.setText("11080, Zemun");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("DOBRO DOŠLI!");

        jMenu1.setText("Korisnik");

        miPrikazPodataka.setText("Prikaz podataka o nalogu");
        miPrikazPodataka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrikazPodatakaActionPerformed(evt);
            }
        });
        jMenu1.add(miPrikazPodataka);

        miLoyaytyKlub.setText("Postanite član loyalty kluba");
        miLoyaytyKlub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoyaytyKlubActionPerformed(evt);
            }
        });
        jMenu1.add(miLoyaytyKlub);

        miPretragaNaloga.setText("Pretraga naloga");
        miPretragaNaloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaNalogaActionPerformed(evt);
            }
        });
        jMenu1.add(miPretragaNaloga);

        miPretragaClanova.setText("Pretraga članova");
        miPretragaClanova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaClanovaActionPerformed(evt);
            }
        });
        jMenu1.add(miPretragaClanova);

        miLogout.setText("Odjavite se");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Predstave");

        miPredstave.setText("Prikaz repertoara");
        miPredstave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPredstaveActionPerformed(evt);
            }
        });
        jMenu2.add(miPredstave);

        miPretrazi.setText("Pretraži predstave");
        miPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziActionPerformed(evt);
            }
        });
        jMenu2.add(miPretrazi);

        miRezervacija.setText("Rezervacija karte");
        miRezervacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRezervacijaActionPerformed(evt);
            }
        });
        jMenu2.add(miRezervacija);

        miKupovina.setText("Kupovina karte");
        miKupovina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKupovinaActionPerformed(evt);
            }
        });
        jMenu2.add(miKupovina);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(lblPozoriste, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblPozoriste)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLoyaytyKlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoyaytyKlubActionPerformed
        new LoyaltyClubForm(n).setVisible(true);
    }//GEN-LAST:event_miLoyaytyKlubActionPerformed

    private void miPredstaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPredstaveActionPerformed
        new RepertoarForm(n).setVisible(true);
    }//GEN-LAST:event_miPredstaveActionPerformed

    private void miRezervacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRezervacijaActionPerformed
//        new RezervacijeFormdeleted(n).setVisible(true);
        new RezervacijeForm(n).setVisible(true);
    }//GEN-LAST:event_miRezervacijaActionPerformed

    private void miKupovinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKupovinaActionPerformed
        new KupovinaForm(n).setVisible(true);
    }//GEN-LAST:event_miKupovinaActionPerformed

    private void miPrikazPodatakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrikazPodatakaActionPerformed
        JOptionPane.showMessageDialog(this, n.toString());
    }//GEN-LAST:event_miPrikazPodatakaActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miPretragaNalogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaNalogaActionPerformed
        new PretragaNalogaForm(n).setVisible(true);
    }//GEN-LAST:event_miPretragaNalogaActionPerformed

    private void miPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziActionPerformed
        if(n.getNalogID() == 1){
            new PredstaveForm(n).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Ovoj sekciji ima pristup samo administrator!");
            return;
        }
        
        
    }//GEN-LAST:event_miPretraziActionPerformed

    private void miPretragaClanovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaClanovaActionPerformed
        new PretragaClanovaKlubaForm(n).setVisible(true);
    }//GEN-LAST:event_miPretragaClanovaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPozoriste;
    private javax.swing.JMenuItem miKupovina;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miLoyaytyKlub;
    private javax.swing.JMenuItem miPredstave;
    private javax.swing.JMenuItem miPretragaClanova;
    private javax.swing.JMenuItem miPretragaNaloga;
    private javax.swing.JMenuItem miPretrazi;
    private javax.swing.JMenuItem miPrikazPodataka;
    private javax.swing.JMenuItem miRezervacija;
    // End of variables declaration//GEN-END:variables
}
