/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form.gledalac;

import controller.ControllerClient;
import domain.Gledalac;
import domain.Nalog;
import java.net.SocketException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marij
 */
public class GledalacForm extends javax.swing.JDialog {
    
    Gledalac g;
    /**
     * Creates new form NalogForm
     */
    public GledalacForm(java.awt.Frame parent, boolean modal, Gledalac g) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.g = g;
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
        txtGledalacID.setText(String.valueOf(g.getGledalacID()));
        txtImePrezime.setText(g.getImePrezime());
        txtDatumRodjenja.setText(sdf.format(g.getDatumRodjenja()));
        txtBrojTelefona.setText(g.getBrojTelefona());
        lblNalog.setText(g.getNalog().getKorisnickoIme());
        
        txtGledalacID.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOtkazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblBrojTelefona = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblImePrezime = new javax.swing.JLabel();
        lblGledalacID = new javax.swing.JLabel();
        txtGledalacID = new javax.swing.JTextField();
        txtImePrezime = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JFormattedTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        lblNal = new javax.swing.JLabel();
        lblNalog = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPozoriste = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pozorište \"Gardoš\" - Član loyalty kluba");

        btnOtkazi.setText("Nazad");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni podatke");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Prekini članstvo");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o članu loyalty kluba"));

        lblBrojTelefona.setText("Broj telefona:");

        lblDatumRodjenja.setText("Datum rođenja:");

        lblImePrezime.setText("Ime i prezime:");

        lblGledalacID.setText("GledalacID:");

        lblNal.setText("Nalog:");

        lblNalog.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumRodjenja)
                    .addComponent(lblImePrezime)
                    .addComponent(lblGledalacID)
                    .addComponent(lblBrojTelefona)
                    .addComponent(lblNal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNalog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(txtGledalacID)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBrojTelefona))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNal)
                    .addComponent(lblNalog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGledalacID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGledalacID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImePrezime))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumRodjenja))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojTelefona)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/logo_pozoriste.png"))); // NOI18N

        lblPozoriste.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblPozoriste.setText("POZORIŠTE \"GARDOŠ\"");

        jLabel6.setText("Sibinjanin Janka bb");

        jLabel7.setText("11080, Zemun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblPozoriste, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOtkazi)
                        .addGap(157, 157, 157))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblPozoriste)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnObrisi))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOtkazi)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        try {

            if (txtImePrezime.getText().isEmpty()  ||  txtBrojTelefona.getText().isEmpty() || txtDatumRodjenja.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Sva polja su obavezna!");
                return;
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            
            String staroImePrezime = g.getImePrezime();
            String stariBrojTelefona = g.getBrojTelefona();
            String stariDatumRodjenja = sdf.format(g.getDatumRodjenja());
            
            String novoImePrezime = txtImePrezime.getText();
            String noviBrojTelefona = txtBrojTelefona.getText();
            Date noviDatumRodjenja = sdf.parse(txtDatumRodjenja.getText());
            
            g.setImePrezime(novoImePrezime);
            g.setBrojTelefona(noviBrojTelefona);
            g.setDatumRodjenja(noviDatumRodjenja);
            
            

            if (!g.getImePrezime().equals(staroImePrezime) && !g.getBrojTelefona().equals(stariBrojTelefona) && !g.getDatumRodjenja().equals(stariDatumRodjenja)) {
                try {                    
                    ControllerClient.getInstance().updateGledalac(g);
                    JOptionPane.showMessageDialog(this, "Uspesno izmenjeni podaci!");
                } catch (Exception ex) {
                    Logger.getLogger(GledalacForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            PretragaClanovaKlubaForm pc = (PretragaClanovaKlubaForm) getParent();
            pc.osveziTabelu();
            this.dispose();
        } catch (Exception ex) {

            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(rootPane, "Komunikacija izmedju servera je prekinuta");
                this.dispose();
                System.exit(0);
            }
            Logger.getLogger(GledalacForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        try {

            int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da prekinete članstvo?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                ControllerClient.getInstance().deleteGledalac(g);
                JOptionPane.showMessageDialog(this, "Uspešno prekinuto članstvo!");
                PretragaClanovaKlubaForm pc = (PretragaClanovaKlubaForm) getParent();
                pc.osveziTabelu();
                this.dispose();
            }

        } catch (Exception ex) {

            if (ex instanceof SocketException) {
                JOptionPane.showMessageDialog(rootPane, "Komunikacija izmedju servera je prekinuta");
                this.dispose();
                System.exit(0);
            }

            Logger.getLogger(GledalacForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnObrisiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrojTelefona;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblGledalacID;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JLabel lblNal;
    private javax.swing.JLabel lblNalog;
    private javax.swing.JLabel lblPozoriste;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JFormattedTextField txtDatumRodjenja;
    private javax.swing.JTextField txtGledalacID;
    private javax.swing.JTextField txtImePrezime;
    // End of variables declaration//GEN-END:variables


   

 


}
