/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form.gledalac;


import controller.ControllerClient;
import domain.Gledalac;
import domain.Nalog;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author marij
 */
public class LoyaltyClubForm extends javax.swing.JFrame {

    Nalog n;
    
    /**
     * Creates new form LoyaltyClubForm
     */
    public LoyaltyClubForm(Nalog n) {
        initComponents();
        setLocationRelativeTo(null);
        this.n = n;
        txtNalog.setText(n.getKorisnickoIme());
        txtNalog.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblPozoriste = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblImeIPrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblBrojTelefona = new javax.swing.JLabel();
        txtImeIPrezime = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        btnUclaniSe = new javax.swing.JButton();
        txtBrojTelefona = new javax.swing.JTextField();
        btnOtkazi = new javax.swing.JButton();
        lblNalog = new javax.swing.JLabel();
        txtNalog = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pozorište \"Gardoš\" - Loyalty klub");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/logo_pozoriste.png"))); // NOI18N

        lblPozoriste.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblPozoriste.setText("POZORIŠTE \"GARDOŠ\"");

        jLabel6.setText("Sibinjanin Janka bb");

        jLabel7.setText("11080, Zemun");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Postanite član našeg loyalty kluba"));

        lblImeIPrezime.setText("Ime i prezime:");

        lblDatumRodjenja.setText("Datum rodjenja:");

        lblBrojTelefona.setText("Broj telefona:");

        txtImeIPrezime.setText("Ana Anic");

        txtDatumRodjenja.setText("01.01.1999.");

        btnUclaniSe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUclaniSe.setText("Učlanite se");
        btnUclaniSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUclaniSeActionPerformed(evt);
            }
        });

        txtBrojTelefona.setText("0601234567");

        btnOtkazi.setText("Otkazi");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        lblNalog.setText("Nalog:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrojTelefona)
                            .addComponent(lblImeIPrezime)
                            .addComponent(lblDatumRodjenja)
                            .addComponent(lblNalog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtImeIPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBrojTelefona, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(txtNalog)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addComponent(btnUclaniSe)
                        .addGap(36, 36, 36)
                        .addComponent(btnOtkazi)
                        .addGap(136, 136, 136)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNalog)
                    .addComponent(txtNalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtImeIPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImeIPrezime)
                        .addGap(18, 18, 18)
                        .addComponent(lblDatumRodjenja)
                        .addGap(18, 18, 18)
                        .addComponent(lblBrojTelefona)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUclaniSe)
                    .addComponent(btnOtkazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(lblPozoriste, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblPozoriste)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUclaniSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUclaniSeActionPerformed
        try {
            if(txtImeIPrezime.getText().isEmpty() || txtDatumRodjenja.getText().isEmpty() || txtBrojTelefona.getText().isEmpty() || txtNalog.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
                return;
            }
            
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            
            String imePrezime = txtImeIPrezime.getText();
            Date datumRodjenja = sdf.parse(txtDatumRodjenja.getText());
            String brojTelefona = txtBrojTelefona.getText();
            
            int gledalacID = vratiGledalacID();
            
            Gledalac g = new Gledalac(gledalacID, imePrezime, datumRodjenja, brojTelefona, n);            

            boolean registrovan = (boolean) ControllerClient.getInstance().loyalty(g);
            
            if(registrovan){
                JOptionPane.showMessageDialog(this, "Uspešno ste se učlanili!");
            }else{ 
                JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom učlanjenja...");
            }
        } catch (ParseException ex) {
            Logger.getLogger(LoyaltyClubForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(LoyaltyClubForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUclaniSeActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnUclaniSe;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrojTelefona;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblImeIPrezime;
    private javax.swing.JLabel lblNalog;
    private javax.swing.JLabel lblPozoriste;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtImeIPrezime;
    private javax.swing.JTextField txtNalog;
    // End of variables declaration//GEN-END:variables



    private int vratiGledalacID() throws Exception {

        int gledalacID = (int) ControllerClient.getInstance().vratiGledalacID();
        
        return gledalacID;
    }
}
