/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form.racun;

import controller.ControllerClient;
import domain.Karta;
import domain.Nalog;
import domain.Predstava;
import domain.Racun;
import domain.Rezervacija;
import java.util.Date;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.form.karta.KupiKartu;
import view.form.karta.KupovinaForm;

/**
 *
 * @author marij
 */
public class RacunForm extends javax.swing.JDialog {

    Karta k;
    Nalog n;
    Predstava p;
    Rezervacija r;
    /**
     * Creates new form RacunForm
     */
    public RacunForm(java.awt.Frame parent, boolean modal, Karta k, Nalog n, Predstava p, Rezervacija r) {
        super(parent, modal);
        initComponents();
        this.k = k;
        this.n = n;
        this.p = p;
        this.r = r;
        lblNalog.setText(n.getKorisnickoIme());
        if(r != null){
            txtIznos.setText(String.valueOf((k.getCena()) * r.getBrojKarata()));
        }else{
            txtIznos.setText(String.valueOf(k.getCena()));
        }
        
        txtIznos.setEditable(false);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblPozoriste = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblNalog = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblIznos = new javax.swing.JLabel();
        btnPlati = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        lblZiroRacun = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        txtZiroRacun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pozorište \"Gardoš\" - Transakcija");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/form/logo_pozoriste.png"))); // NOI18N

        lblPozoriste.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblPozoriste.setText("POZORIŠTE \"GARDOŠ\"");

        jLabel6.setText("Sibinjanin Janka bb");

        jLabel7.setText("11080, Zemun");

        jLabel1.setText("Zdravo, ");

        lblNalog.setText("jLabel4");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Plaćanje karte"));

        lblIznos.setText("Iznos:");

        btnPlati.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPlati.setText("Plati kartu");
        btnPlati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatiActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        lblZiroRacun.setText("Ziro racun:");

        txtIznos.setText("750,00");

        txtZiroRacun.setText("200123456789");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblZiroRacun)
                        .addGap(18, 18, 18)
                        .addComponent(txtZiroRacun))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIznos)
                        .addGap(46, 46, 46)
                        .addComponent(txtIznos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPlati)
                        .addGap(33, 33, 33)
                        .addComponent(btnNazad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznos)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZiroRacun)
                    .addComponent(txtZiroRacun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlati)
                    .addComponent(btnNazad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblPozoriste, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNalog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblPozoriste)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNalog))
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatiActionPerformed

        
        try {
            if(txtIznos.getText().isEmpty() || txtZiroRacun.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
                return;
            }
            double iznos = Double.parseDouble(txtIznos.getText());
            String ziroRacun = txtZiroRacun.getText();
            
            int racunID = vratiRacunID();
            
            Racun r = new Racun(p, n, racunID, new Date(), iznos, ziroRacun, k);
            
            boolean uspesno = ControllerClient.getInstance().sacuvajRacun(r);
            
            if(uspesno){

                
                if(getParent() instanceof KupiKartu){
                    KupiKartu kk = (KupiKartu) getParent();
                    kk.dodajKartu(k);
                }else{
                    KupovinaForm kf = (KupovinaForm) getParent();
                    kf.dodajKartu(k);
                }
                
                JOptionPane.showMessageDialog(this, r.toString());
            }else{
                JOptionPane.showMessageDialog(this, "Došlo je do greške prilikom obrade transakcije!");
            }
            
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(RacunForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPlatiActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPlati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblNalog;
    private javax.swing.JLabel lblPozoriste;
    private javax.swing.JLabel lblZiroRacun;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtZiroRacun;
    // End of variables declaration//GEN-END:variables

    private int vratiRacunID() throws Exception {
        int racunID = (int) ControllerClient.getInstance().vratiRacunID();
        
        return racunID;
    }
}
